### ISSUE TITLE
Best Score Bug.

### ISSUE THREAD

**Issue by WalkingBread** [WalkingBread/Snake2D#4]
Well, as I had recently added new class, which allows to store scores and compute the best one, there has appeared a new bug. Luckily it doesn't seem to be very serious. It will have been dealt with by the end of the week, I hope.

**Comment by michalwa** [comment]
As soon as I'd implemented a new class, I've started to talk very formally. I haven't even thought of actually describing the bug. Now I'm stuck in this prison of mine battling misconceptions and trying as hard as I can to **obey  the  rules**.
